// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function cardSuitLabel(suitStr) {
  switch (suitStr) {
    case "C" :
        return "Clubs";
    case "D" :
        return "Diamonds";
    case "H" :
        return "Hearts";
    case "S" :
        return "Spades";
    default:
      return ;
  }
}

function cardValueLabel(valueStr) {
  switch (valueStr) {
    case "10" :
        return "Ten";
    case "2" :
        return "Two";
    case "3" :
        return "Three";
    case "4" :
        return "Four";
    case "5" :
        return "Five";
    case "6" :
        return "Six";
    case "7" :
        return "Seven";
    case "8" :
        return "Eight";
    case "9" :
        return "Nine";
    case "A" :
        return "Ace";
    case "J" :
        return "Jack";
    case "K" :
        return "King";
    case "Q" :
        return "Queen";
    default:
      return ;
  }
}

function cardSuitIcon(suitStr) {
  switch (suitStr) {
    case "C" :
        return "Clubs";
    case "D" :
        return "Diamonds";
    case "H" :
        return "Hearts";
    case "S" :
        return "Spades";
    default:
      return "-- unknown suit --";
  }
}

exports.cardSuitLabel = cardSuitLabel;
exports.cardValueLabel = cardValueLabel;
exports.cardSuitIcon = cardSuitIcon;
/* No side effect */
